### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by andrewc2** [MyTwitterBots/MyTwitterBots.github.io#1]
I run a discord bot for a couple Taylor Swift servers and recently implemented a simple store command using the products json, but see you have more available information you're tracking. I've been hoping to be able to have a kinda similar auto poster just when new things are added, so I was wondering if you could possibly message me about how you've implemented your bot? I've got the same username on twitter, or perhaps you have a repo for the bot you could share?

**Comment by MyTwitterBots** [comment]
Hey there, yeah should be totally doable to connect it to a discord server.  I just threw the files into this repository https://github.com/cashcat96/ShopifyJsonMonitor

**Comment by andrewc2** [comment]
Neat, thanks I'll take a look!
