### ISSUE TITLE
Small query.

### ISSUE THREAD

**Issue by krishmurjani** [MyTwitterBots/MyTwitterBots.github.io#2]
I just wanted to know, is it possible for you to share when exactly the Store bot gets triggered? Please let me know! Thanks!

**Comment by MyTwitterBots** [comment]
The bots get triggered when products go in or out of stock, or when the number of products changes (possible new product added).  The products and in-stock info can be viewed in the <store base url>/products.json file.

**Comment by krishmurjani** [comment]
Is the /products.json file public?

**Comment by MyTwitterBots** [comment]
yup, as long as the store webpage uses shopify, you can just put /products.json at the end of the url and you'll see the file.  e.g. https://store.taylorswift.com/products.json

**Comment by krishmurjani** [comment]
Thank you so much!
